version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # 백엔드 서비스 (필요시 주석 해제)
  # backend:
  #   image: your-backend-image
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - app-network

# networks:
#   app-network:
#     driver: bridge
